/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/configuration': typeof ConfigurationRoute
  '/events': typeof EventsRoute
  '/markets': typeof MarketsRoute
  '/orders': typeof OrdersRoute
  '/positions': typeof PositionsRoute
  '/risk': typeof RiskRoute
  '/runtime': typeof RuntimeRoute
  '/strategies': typeof StrategiesRoute
  '/system': typeof SystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/configuration': typeof ConfigurationRoute
  '/events': typeof EventsRoute
  '/markets': typeof MarketsRoute
  '/orders': typeof OrdersRoute
  '/positions': typeof PositionsRoute
  '/risk': typeof RiskRoute
  '/runtime': typeof RuntimeRoute
  '/strategies': typeof StrategiesRoute
  '/system': typeof SystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/configuration': typeof ConfigurationRoute
  '/events': typeof EventsRoute
  '/markets': typeof MarketsRoute
  '/orders': typeof OrdersRoute
  '/positions': typeof PositionsRoute
  '/risk': typeof RiskRoute
  '/runtime': typeof RuntimeRoute
  '/strategies': typeof StrategiesRoute
  '/system': typeof SystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/configuration'
    | '/events'
    | '/markets'
    | '/orders'
    | '/positions'
    | '/risk'
    | '/runtime'
    | '/strategies'
    | '/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/configuration'
    | '/events'
    | '/markets'
    | '/orders'
    | '/positions'
    | '/risk'
    | '/runtime'
    | '/strategies'
    | '/system'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/configuration'
    | '/events'
    | '/markets'
    | '/orders'
    | '/positions'
    | '/risk'
    | '/runtime'
    | '/strategies'
    | '/system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ConfigurationRoute: typeof ConfigurationRoute
  EventsRoute: typeof EventsRoute
  MarketsRoute: typeof MarketsRoute
  OrdersRoute: typeof OrdersRoute
  PositionsRoute: typeof PositionsRoute
  RiskRoute: typeof RiskRoute
  RuntimeRoute: typeof RuntimeRoute
  StrategiesRoute: typeof StrategiesRoute
  SystemRoute: typeof SystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ConfigurationRoute: ConfigurationRoute,
  EventsRoute: EventsRoute,
  MarketsRoute: MarketsRoute,
  OrdersRoute: OrdersRoute,
  PositionsRoute: PositionsRoute,
  RiskRoute: RiskRoute,
  RuntimeRoute: RuntimeRoute,
  StrategiesRoute: StrategiesRoute,
  SystemRoute: SystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
